name: Deploy Project
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"                          
      - name: Update Controle Online      
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.CONTROLEONLINE }}
          port: ${{ secrets.PORT }}        
          script: |
                  cd ~/sistemas/controleonline/api/modules/controleonline/users
                  git checkout master
                  git pull origin master
                  cd ~/sistemas/controleonline/api/
                  php bin/console cache:clear